services:
  db:
    image: postgres:15
    container_name: nagara_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: nagara_user
      POSTGRES_PASSWORD: nagara_pass
      POSTGRES_DB: nagara_db
    networks:
      - nagara_net

  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: nagara_django
    volumes:
      - ./backend:/app
      - ./backend/staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - nagara_net

  fastapi:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
    container_name: nagara_fastapi
    volumes:
      - ./backend:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - nagara_net

volumes:
  postgres_data:

networks:
  nagara_net:
    driver: bridge
